name: CI Backend

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  backend:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Update Rust toolchain
        run: rustup update stable

      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: "ci"

      - name: Install Rust components
        run: rustup component add rustfmt clippy

      - name: Install cntryl-tools
        run: cargo install --git https://github.com/cntryl/tools --rev d36dc1c09462a4fd691ed9fdcc4413eb61f0c80c --locked cntryl-tools

      - name: Cargo build
        run: cargo build --locked

      - name: Cargo test
        run: cargo test --locked

      - name: Cargo clippy pedantic
        run: cargo clippy --locked --workspace --all-targets --all-features -- -D warnings -D clippy::pedantic

      - name: Cargo fmt check
        run: cargo fmt --all -- --check

      - name: Validate tests
        run: |
          find tests -type f -name '*.rs' -print0 | while IFS= read -r -d '' file; do
            cntryl-tools validate-tests -f "$file"
          done
